import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import experiencesRoutes from './routes/experiences.js';
import bookingsRoutes from './routes/bookings.js';
import promoRoutes from './routes/promo.js';
dotenv.config();
console.log("DATABASE_URL:", process.env.DATABASE_URL);
const app = express();
app.use(cors()); app.use(express.json());
app.use('/api/experiences', experiencesRoutes);
app.use('/api/bookings', bookingsRoutes);
app.use('/api/promo', promoRoutes);
app.get('/api/health', (req,res)=>res.json({status:'OK'}));
app.listen(process.env.PORT || 5000, ()=>console.log('Server running'));